### ISSUE TITLE
Add auth token support?

### ISSUE THREAD

**Issue by shanna** [nats-io/pure-ruby-nats#10]
Passing a token in the server URL results in a `CONNECT` message to the server with `user` & `pass` not `auth_token`. I thought there might be an alternate interface `auth_token` doesn't show up anywhere in the client.rb code and the auth spec currently doesn't test for it?

My gnatsd server is logging an `Authorization Error` so I'm guessing a `user` with a null `password` isn't treated the same as `auth_token`.

**Comment by wallyqs** [comment]
Fixed via #11
