### ISSUE TITLE
multi home network handling not falling back to v4

### ISSUE THREAD

**Issue by ripienaar** [nats-io/pure-ruby-nats#3]
Great work on this client very happy with how this is going.

The old EM client had some ipv6 issues I didn't mention since they were really EM issues, but since you now 'own' the whole space it's worth mentioning :)

Given a setup where I connect to a host by name and the name resolves to a v4 and a v6 address. It tries the v6 network first thats fine.

But should some node be single homed or having some networking issue - it will fail here.   https://github.com/nats-io/pure-ruby-nats/blob/60a958b896a219cf0e5dbf9cd7132d4b1959e50a/lib/nats/io/client.rb#L1064:

```
#<Errno::ENETUNREACH: Network is unreachable - connect(2) for [x:x::x:x:x:5cac]:4222>
```

This is particularly bad on v4 only hosts where the name I am connecting to has a v6 and a v4 name.  Since on those nodes it will only ever try the v6 address and fail forever never trying the v4s where it would work.

Here you'd need to somehow handle that and try the v4 address instead :(

And to be correct you should try the v6 address and when you cant fail there try the v4 address on the exact same hostname, if that fails, move to the new server and do the same again.  This way should there be a connectivity issue on say v6 stack but the v4 stack still works, it'll be able to connect rather than bail on the first error.

Further I also noticed that this particular failure happens early enough that it breaks the retry sleep behaviour...the failure is here https://github.com/nats-io/pure-ruby-nats/blob/60a958b896a219cf0e5dbf9cd7132d4b1959e50a/lib/nats/io/client.rb#L181 notice that `:was_connected` is still not set here this means `should_delay_connect?` will be false and https://github.com/nats-io/pure-ruby-nats/blob/60a958b896a219cf0e5dbf9cd7132d4b1959e50a/lib/nats/io/client.rb#L564 never sleeps, so in early network errors like this you get a tight never ending never sleeping loop

Further none of the `on_*` callbacks are being fired anywhere along this failure path meaning this failure is completely opaque to the outside world https://github.com/nats-io/pure-ruby-nats/blob/60a958b896a219cf0e5dbf9cd7132d4b1959e50a/lib/nats/io/client.rb#L199 should probably get some `on_error` there?

Let me know if you'd rather I pull these into separate issues.

**Comment by ripienaar** [comment]
After some more digging into this I think the problem is much simpler luckily

  * it IS connecting to all the addresses, v4 and v6, so thats great
  * it is not always trying the v6 address before the v4 address, this is probably wrong but lets ignore that for now, I could make that into a different ticket
  * When connecting it always tries all the servers found in DNS and doesn't stop when it finds a good connection https://github.com/nats-io/pure-ruby-nats/blob/60a958b896a219cf0e5dbf9cd7132d4b1959e50a/lib/nats/io/client.rb#L972 

So simply changing that to:

```
        addrinfo.each_with_index do |ai, i|
          begin
            @socket = connect_addrinfo(ai, @uri.port, @connect_timeout)
            break
          rescue SystemCallError
            # Give up if no more available
            raise if addrinfo.length == i+1
          end
        end
```

ie. breaking if the socket `connect_addrinfo` doesn't raise any errors - ie. we're connected - then this all works

Some extra error callbacks would still be good

**Comment by ripienaar** [comment]
PR addresses the stuff I mentioned - except for the V6 first.

@wallyqs you're free to discard and do whatever you prefer, there doesnt seem to be test coverage for the Socket class so I didnt add any tests

**Comment by wallyqs** [comment]
Good catch... Merged your changes after adding some minor changes to the spec. I will take a look at the ipv4/ipv6 connection preference and update here too. Thanks for the PR and the feedback!

**Comment by wallyqs** [comment]
Seems that since right now we are relying on the default behavior from `Socket.getaddrinfo` for the ordering of the list of endpoints to attempt to connect, and since it looks like that result already went through from what is defined in the [RFC-3484](https://www.ietf.org/rfc/rfc3484.txt) and [RFC-6724](https://tools.ietf.org/html/rfc6724) standards, think we can probably leave as is for now, and letting the user determine the ipv6 ordering by tuning `/etc/gai.conf` to set the precedence of address families to try when connecting as it is suggested in those RFCs.

**Comment by ripienaar** [comment]
That's what I thought but my machines are configured for IPv6 priority already - and works for other stuff. Not to worry I will investigate further and if I can narrow it down to either environment or code I will make a new ticket. For now happy to close this one

**Comment by wallyqs** [comment]
As a separate issue sounds good for now, we could add a `sort_by`  ipv6 before attempting to connect ( (https://github.com/wallyqs/pure-ruby-nats/commit/48dfda9d5967fc17832e565817e3ee64ff368937)[example]) so that those addresses are tried first but just not sure whether that is correct. Thanks again.

**Comment by ripienaar** [comment]
Yeah, I'll investigate more - probably in a few weeks.

Happy to close this and hopefully we get a release soon :)

**Comment by wallyqs** [comment]
Published new release of the gem with your fixes so closing this one for now, thanks!
https://github.com/nats-io/pure-ruby-nats/releases/tag/v0.1.2
